import { Button, VerticalBox, HorizontalBox ,Slider, StandardListView, ProgressIndicator } from "std-widgets.slint";




//enum for the UI main parameters
global SystemService {
	
	in-out property <int> global_width : 800;
	in property <int> global_height : 600;
	in-out property <length> global_width_length : global_width * 1px;
	in-out property <length> global_height_length : global_height * 1px;
	
	callback request_needle_pos();
}

// Popup for the user to choose a song from a list of files inside a directory defined backend
component LoadFile inherits Rectangle {
	
	callback from-app-request-load-file();
	callback from-app-request-fetch-directory();
	callback from-app-request-user-selected-file(int);

	callback from-app-request-import-file();
	in property <[StandardListViewItem]> file_model;
	in property <string> selected_file;

	popup_select := PopupWindow {

		close-policy: no-auto-close; 

  	Rectangle { 
			height: SystemService.global_height_length * 0.8; 
			width: SystemService.global_width_length * 0.8; 
			background: grey;

			VerticalLayout {
					StandardListView {
						model: root.file_model;
						current-item-changed(current-item) => {from-app-request-user-selected-file(current-item)}
					}

					Text {
						text: root.selected_file;
					}
				HorizontalBox {
					Button {
						text: "Close";
						clicked => popup_select.close(); 
					}
					Button {
						text: "Confirm";
						clicked => {
							root.from-app-request-load-file();
							popup_select.close();
						}
					}
				}
			}
		}
    x: SystemService.global_width_length * 0.2; 
		y: SystemService.global_width_length * 0.2; 
		height: SystemService.global_width_length * 0.8; 
		width: SystemService.global_height_length * 0.8; 
  }
	
 
	VerticalBox {
		Rectangle {
			height: 15%;
			Text {
				text: "Supported formats: mp3, wav & ogg";
				vertical-alignment: center; 

			}
		}

		Button {
			text: "Play from project folder..."; 
			clicked => {
				root.from-app-request-fetch-directory();
				popup_select.show();
			}
		}

		Button {
			text: "Import file from your home directory..."; 
			clicked => {
				root.from-app-request-import-file();	
			} 
		}
	}

}

// main component 
export component AppWindow inherits Window {
	width: SystemService.global_width_length;
	height: SystemService.global_height_length; 
	
	callback request-load-popup();
	callback request-load-file();
	callback request-fetch-directory();
	callback request-user-selected-file(int);
	callback request-import-file();

	callback request-progress-bar() ; 

	callback request-play-pause();
	callback request-stop();
	callback request-change-volume(float);

	in property <[StandardListViewItem]> file_model;
	in property <string> selected_file : "File selected : None";
	in property <string> selected_file_title : "Media Title will be displayed here";
	

	in property <float> progress_indicator : 0.0;
	in property <bool> is_playing : false;
	// timer for the progress bar 
	timer := Timer {
		interval: 100ms; 
		running: is_playing; 
		triggered => {
			root.request-progress-bar();
		}
	}

	VerticalLayout {
			HorizontalLayout {
					LoadFile {
						from-app-request-load-file => {root.request-load-file()}
						from-app-request-fetch-directory => {root.request-fetch-directory()}
						from-app-request-user-selected-file(index) => {root.request-user-selected-file(index)}
						from-app-request-import-file => {root.request-import-file()}
						file_model: file_model;
						selected_file: selected_file;
					}

					Text {
						wrap: word-wrap; 
							text: root.selected_file_title;
							horizontal-alignment: center;
							vertical-alignment: center; 
							font-size: 20px;
					}
			}
			VerticalBox {
				HorizontalBox {
					Button {
						text: "Stop"; 
						clicked =>
							root.request-stop();
					}
					Button {
						text: "Play/Pause";
						clicked => {
							root.request-play-pause();
						}
					}
				}
				Rectangle {
					height:10%;
					Text{
						text: "Progress Bar";
						horizontal-alignment: center;
						vertical-alignment: center;
					}
				}
				ProgressIndicator {
					width: 90%; 
					height: 40px;

					progress: root.progress_indicator; 
					
				}

			}

			HorizontalLayout {
				height: 15%;
				Text {
					text: "Volume slider :";
					vertical-alignment: center;
				}
				Slider {
					minimum: 0;
					maximum: 100;
					value: 50; 
					released(value) => {
						debug("(UI) : volume slider value changed : ", value);
						root.request-change-volume(value);
					}
				}
			}	
	}
}



